apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hrg4m9a1b-go
  janus-idp.io/tekton: hrg4m9a1b-go
  backstage.io/kubernetes-id: hrg4m9a1b-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hrg4m9a1b-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
